name: Run Go tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.3
      
      - name: List files and folders
        run: ls -la
      
      - name: Build app
        run: cd ./backend && ls -la && CGO_ENABLED=0 GOOS=linux go build -o ./cmd/web

      - name: Run tests
        run: go test -v ./backend/...